---
RecipeFormatVersion: "2020-01-25"
ComponentName: "CameraComponent"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is camera component to capture snapshots in jpg"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ">=2.0.0 <3.0.0"
    DependencyType: "HARD"
  com.example.ShadowManager:
    VersionRequirement: ">=1.0.0 <1.1.0"
    DependencyType: "HARD"

ComponentConfiguration:
  DefaultConfiguration:
    Message: "World"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.example.CameraComponent.zip"
        Unarchive: ZIP
    Lifecycle:
      RequiresPrivilage: true
      Run: "sudo python3 -u {artifacts:decompressedPath}/com.example.CameraComponent/main.py {configuration:/Message}"