---
RecipeFormatVersion: "2020-01-25"
ComponentName: "CameraComponent"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is camera component to capture snapshots in jpg"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "World"
    accessControl:
      aws.greengrass.ShadowManager:
        'com.example.CameraComponent:shadow:1':
          policyDescription: 'Allows access to shadows'
          operations:
            - 'aws.greengrass#GetThingShadow'
            - 'aws.greengrass#UpdateThingShadow'
            - 'aws.greengrass#DeleteThingShadow'
          resources:
            - $aws/things/{iot:thingName}/shadow
            - $aws/things/{iot:thingName}/shadow/name/rpi4-desk
        'com.example.CameraComponent:shadow:2':
          policyDescription: 'Allows access to things with shadows'
          operations:
            - 'aws.greengrass#ListNamedShadowsForThing'
          resources:
            - {iot:thingName}
      aws.greengrass.ipc.pubsub:
        'com.example.CameraComponent:pubsub:1':
          policyDescription: 'Allows access to shadow pubsub topics'
          operations:
            - 'aws.greengrass#SubscribeToTopic'
          resources:
            - $aws/things/{iot:thingName}/shadow/get/accepted
            - $aws/things/{iot:thingName}/shadow/name/rpi4-desk/get/accepted
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.example.CameraComponent.zip"
        Unarchive: ZIP
    Lifecycle:
      Run: "sudo python3 -u {artifacts:decompressedPath}/com.example.CameraComponent/main.py {configuration:/Message}"